name: Wakatime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: dvjn/wakatime-charts@master
        with:
          COMMIT_MESSAGE: "update(wakatime): stats charts"
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: Anish-Shobith
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # only required if using the action in repository other than profile