name: Wakatime

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:
  update-readme:
    name: Update wakatime stats.
    runs-on: ubuntu-latest
    steps:
      - name: Wakatime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOWS_OS: "True"
          SHOW_PROJECTS: "True"
          COMMIT_BY_ME: "True"
          COMMIT_USERNAME: Anish-Shobith
          COMMIT_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # only required if using the action in repository other than profile