name: Wakatime

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:
  update-readme:
    name: Update wakatime stats.
    runs-on: ubuntu-latest
    steps:
      - name: Install GPG
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg

      - name: Sign commit with GPG key
        uses: actions/gpg-sign@v2
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Wakatime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOWS_OS: "True"
          SHOW_PROJECTS: "True"
          COMMIT_BY_ME: "True"
          SHOW_COMMIT: "True"
          COMMIT_USERNAME: "Anish-Shobith"
          COMMIT_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # only required
